server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/artfulescape}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  jwt:
    secret: ${JWT_SECRET:change-me}
    expirationMillis: ${JWT_EXPIRATION_MILLIS:2592000000} # 30 days
  cors:
    allowed-origins: ${FRONTEND_URL:http://localhost:5173}
  razorpay:
    keyId: ${RAZORPAY_KEY_ID:}
    keySecret: ${RAZORPAY_KEY_SECRET:}

logging:
  level:
    org.springframework.security: INFO
